# *Numpy*

In [2]:
import numpy as np

## Compare numpy array with python list

In [3]:
#python list
%timeit [i**2 for i in range(1000)]

34.3 µs ± 142 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [4]:
#Numpy array
arr = np.arange(1000)
%timeit arr**2

709 ns ± 2.71 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [5]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

## Creating a Array

In [6]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

### 2D array

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
#dimension
arr.ndim

2

In [11]:
#shape
arr.shape

(3, 3)

In [13]:
len(arr)

3

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
np.eye(4,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [31]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [35]:
np.random.rand(5)

array([0.38304127, 0.65677321, 0.26167343, 0.71458994, 0.75946338])

In [36]:
np.random.randn(4)

array([ 0.30059588, -1.35979275, -0.82305316, -1.511542  ])

In [56]:
np.random.randint()

2