In [0]:
import numpy as np

# Operations in Numpy

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
a + 1

array([2, 3, 4, 5])

In [5]:
a ** 2

array([ 1,  4,  9, 16])

In [12]:
b = np.ones(4) - a

In [13]:
b

array([ 0., -1., -2., -3.])

In [14]:
a * b

array([  0.,  -2.,  -6., -12.])

In [16]:
a.dot(a)

30

In [17]:
a == b

array([False, False, False, False])

In [18]:
a < b

array([False, False, False, False])

In [19]:
np.array_equal(a, b)

False

In [22]:
a = np.array([1, 1, 0, 0])
b = np.array([1, 0, 1, 0])

In [23]:
np.logical_or(a, b)

array([ True,  True,  True, False])

In [24]:
a = np.arange(5)

In [25]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [26]:
np.log(a)

/var/folders/k4/jw5sfvg95dxgpf3fwyt483j00000gn/T/ipykernel_14807/2987416308.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [27]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

## Simple Mismatch

In [28]:
a = np.arange(4)
a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

## Basic Reductions

In [30]:
x = np.array([1,2,3,4])
np.sum(x)

10

In [31]:
x = np.array([[1,2], [3,4]])
x

array([[1, 2],
       [3, 4]])

In [33]:
x.sum(axis=0)

array([4, 6])

In [34]:
x.sum(axis=1)

array([3, 7])

## Other Reductions

In [36]:
x = np.array([1,2,3,4])

In [41]:
x.min()

1

In [42]:
x.argmin()

0

In [43]:
x.max()

4

In [44]:
x.argmax()

3

## Logical Operations

In [47]:
np.all([True, True, False, False])

False

In [48]:
np.any([True, True, False, False])

True

In [54]:
a = np.zeros((50, 50))
np.any( a != 0)

False

In [55]:
np.all(a==a)

True

In [56]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])
((a<=b) & (b<=c)).all()

True

## Statistics

In [57]:
x = np.array([1,2,3,1])
y = np.array([[1,2,3], [5,6,1]])
x.mean()

1.75

In [58]:
np.median(x)

1.5

In [61]:
np.median(y, axis=0)

array([3., 4., 2.])

In [66]:
np.median(y, axis=1)

array([2., 5.])

In [67]:
x.std()

0.82915619758885

## EXAMPLE

In [68]:
data = np.loadtxt('data/populations.txt')

In [69]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [70]:
year, hares, lynxes, carrots = data.T

In [84]:
populations = data[:, 1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [82]:
populations.std(axis=1)

array([18176.23601177, 19614.67704439, 24668.33327703, 19225.21492439,
       10030.73055941,  9530.41913501,  9458.79954798, 12319.18106946,
       14923.434219  , 13472.52347888, 15759.51211879, 16967.22330456,
       18751.53327064, 23553.39088586,  5266.87763291, 13018.02169644,
       10757.4263754 , 14578.82787546, 14819.88154099, 13501.68713737,
       15873.31793363])

In [86]:
np.argmax(populations, axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

## Broadcasting

In [92]:
a = np.array([0,1,2])
b = np.array([[0], [10], [20], [30]])

print(a)
print(b)

[0 1 2]
[[ 0]
 [10]
 [20]
 [30]]


In [94]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [96]:
(a + b).T

array([[ 0, 10, 20, 30],
       [ 1, 11, 21, 31],
       [ 2, 12, 22, 32]])

In [97]:
a = np.arange(0, 40, 10)
a

array([ 0, 10, 20, 30])

In [98]:
a = a[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [101]:
a + b

array([[ 0],
       [20],
       [40],
       [60]])

## Array Shape Manipulation

In [103]:
a = np.array([[1,2,3], [4,5,6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [106]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [108]:
b = a.ravel()
b.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

## DIMENSION SUFFLING

In [110]:
a = np.arange(4*3*2).reshape(4,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [120]:
a[0,2,1]

5

In [128]:
a = np.arange(4)
b=a
a.resize((8,))
a

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [129]:
b = np.sort(a)